version: "3.3"

services:
  tree-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true        # for beautiful debug and pretty error output
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_ADDR=http://localhost:3333
    ports:
      - 3000:3000

  proxy:
    image: bitnami/nginx:1.12.0-r0
    ports:
      - 80:80
    restart: always
    links:
      - tree-app
